import { Command } from "commander";
import { readPackageSync } from "read-pkg";
import { generateKeyLayouts, generateKeyboardSvg } from "./lib/index";
import { generateKeymapC } from "./lib/generate-keymap-c";
import { config, initConfig } from "./lib/config";
import {
  listCFlagsPaths,
  updateCCppPropertiesFromCFlags,
} from "./lib/vscode-props";

const pkg = readPackageSync();

const program = new Command();

if (process.env.HELP_WIDTH != null) {
  program.configureHelp({ helpWidth: Number(process.env.HELP_WIDTH) });
}

program
  .name(pkg.name)
  .description(pkg.description || "CLI utilities for QMK and VIA")
  .version(pkg.version);

type Options = {
  config?: string;
};

function applyOptions(options?: Options) {
  if (options == null) {
    return;
  }
  if (options.config) {
    initConfig(options.config);
  }
}

function run(options: Options | undefined, action: () => void) {
  try {
    applyOptions(options);
    action();
  } catch (e) {
    console.error("Error:", e);
    process.exit(1);
  }
}

program
  .command("gen-layout")
  .description(
    "Generate Markdown documentation for a keyboard layout from VIA files",
  )
  .option("-C, --config <path>", "Path to a config file")
  .argument("<outputDir>", "Output directory for generated files")
  .argument("<defPath>", "Path to the VIA definition file (.json)")
  .argument("<savePath>", "Path to the VIA save file (.json)")
  .argument(
    "[optionKeys]",
    "Comma-separated list of option keys or a preset name",
  )
  .action(
    (
      outputDir: string,
      defPath: string,
      savePath: string,
      presetOrValues?: string,
      options?: Options,
    ) => {
      run(options, () => {
        generateKeyLayouts(outputDir, defPath, savePath, presetOrValues);
      });
    },
  );

export interface GenKeyboardOptions extends Options {
  ledByKey?: boolean;
}

program
  .command("gen-keyboard")
  .description("Generate an SVG layout for a keyboard")
  .option("-C, --config <path>", "Path to a config file")
  .option("--led-by-key", "Resolve LED position based on key matrix")
  .argument("<outputDir>", "Output directory for generated files")
  .argument("<infoPath>", "Path to the QMK info.json file")
  .argument("[layoutName]", "Name of the layout to render (optional)")
  .action(
    (
      outputDir: string,
      infoPath: string,
      layoutName?: string,
      options?: GenKeyboardOptions,
    ) => {
      run(options, () =>
        generateKeyboardSvg(outputDir, infoPath, layoutName, options?.ledByKey),
      );
    },
  );

interface GenVscodePropsOptions extends Options {
  workspace: string;
  searchDirs: string;
  userspace: string;
}

program
  .command("gen-vscode-props")
  .description(
    "Generate .vscode/c_cpp_properties.json from CFLAGS generated by QMK during build.",
  )
  .option("-w, --workspace <dir>", "Workspace directory", process.cwd())
  .option(
    "-s, --search-dirs <dirs>",
    "Comma-separated search directories",
    ".,qmk_firmware",
  )
  .option("-u, --userspace <path>", "Path to replace /qmk_userspace with", ".")
  .argument(
    "[cflagsPath]",
    "Path to cflags.txt (if omitted, available cflags files will be listed)",
  )
  .action((cflagsPath: string | undefined, options: GenVscodePropsOptions) => {
    run(options, () => {
      const searchDirs = options.searchDirs.split(",");
      if (cflagsPath == null) {
        listCFlagsPaths(options.workspace, searchDirs);
        return;
      }
      updateCCppPropertiesFromCFlags(
        {
          workspaceDir: options.workspace,
          searchDirs,
          userspacePath: options.userspace,
        },
        cflagsPath,
      );
    });
  });

program
  .command("gen-keymap-c")
  .description("Generate keymap.c from VIA files and QMK info.json")
  .option("-C, --config <path>", "Path to a config file")
  .argument("<outputDir>", "Output directory for generated files")
  .argument("<infoPath>", "Path to the QMK info.json file")
  .argument("<defPath>", "Path to the VIA definition file (.json)")
  .argument("<savePath>", "Path to the VIA save file (.json)")
  .argument("[layoutName]", "Name of the layout macro to use (optional)")
  .action(
    (
      outputDir: string,
      infoPath: string,
      defPath: string,
      savePath: string,
      layoutName?: string,
      options?: Options,
    ) => {
      run(options, () => {
        generateKeymapC(outputDir, infoPath, defPath, savePath, layoutName);
      });
    },
  );

program
  .command("export-config")
  .description("Print the resolved configuration as JSON")
  .action(() => console.log(JSON.stringify(config, null, 2)));

program.parse(process.argv);
